before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docgen
  - publish

.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
      - cryptoapi/build/outputs

build_release:
  <<: *build_template_def
  script:
    - ./gradlew :cryptoapi:assembleRelease --stacktrace

unit_test:
  stage: test
  script:
    - ./gradlew :app:testReleaseUnitTest --stacktrace  -PcryptoApiKey=\"$cryptoApiKey\"
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/reports/tests

pages:
  stage: docgen
  only:
    - release
  script:
    - ./gradlew :cryptoapi:clean :cryptoapi:jvadoc --stacktrace
    - mkdir docs
    - mv cryptoapi/build/javadoc/* docs
  artifacts:
    paths:
      - public

maven_publishing:
  stage: publish
  script:
    - ./gradlew clean bundle -PcryptoApiKey=\"$cryptoApiKey\"
    - ./gradlew bintrayUpload -PbintrayUser=$bintrayUserVar -PbintrayApiKey=$bintrayApiKeyVar -PlibraryVersion=$libraryVersion
  when: manual
