before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - docgen
  - publish

.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
      - cryptoapi/build/outputs
  tags:
    - android

build_release:
  <<: *build_template_def
  script:
    - ./gradlew :cryptoapi:assembleRelease --stacktrace

unit_test:
  stage: test
  script:
    - ./gradlew :app:testReleaseUnitTest --stacktrace  -PcryptoApiKey=\"$cryptoApiKey\"
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/reports/tests
  tags:
    - android

pages:
  stage: docgen
  only:
    - release
  script:
    - ./gradlew :cryptoapi:clean :cryptoapi:javadoc --stacktrace
    - mkdir docs
    - mv cryptoapi/build/javadoc/* docs
  artifacts:
    paths:
      - public
  tags:
    - android

maven_publishing:
  stage: publish
  script:
    - ./gradlew clean
    - ./gradlew :cryptoapi:compileReleaseSources -PlibraryVersion=$CI_COMMIT_TAG
    - ./gradlew :model:build :cryptoapi:build -no-parallel -PlibraryVersion=$CI_COMMIT_TAG
    - ./gradlew bintrayUpload -PbintrayUser=$bintrayUserVar -PbintrayApiKey=$bintrayApiKeyVar -PlibraryVersion=$CI_COMMIT_TAG
  when: manual
  tags:
    - android